In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import sklearn.datasets
import pandas as pd

# Create the Dataframe

In [2]:
df = pd.read_csv("../Resources/heart.csv", sep=";")
df["age"] = (df["age"]/365).apply(np.floor).astype(int)
df.head(20)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0
5,8,60,1,151,67.0,120,80,2,2,0,0,0,0
6,9,60,1,157,93.0,130,80,3,1,0,0,1,0
7,12,61,2,178,95.0,130,90,3,3,0,0,1,1
8,13,48,1,158,71.0,110,70,1,1,0,0,1,0
9,14,54,1,164,68.0,110,60,1,1,0,0,0,0
10,15,61,1,169,80.0,120,80,1,1,0,0,1,0
11,16,51,2,173,60.0,120,80,1,1,0,0,1,0
12,18,40,2,165,60.0,120,80,1,1,0,0,0,0
13,21,54,1,158,78.0,110,70,1,1,0,0,1,0
14,23,39,2,181,95.0,130,90,1,1,1,1,1,0
15,24,45,2,172,112.0,120,80,1,1,0,0,0,1
16,25,58,1,170,75.0,130,70,1,1,0,0,0,0
17,27,45,1,158,52.0,110,70,1,3,0,0,1,0
18,28,47,1,154,68.0,100,70,1,1,0,0,0,0
19,29,59,2,162,56.0,120,70,1,1,1,0,1,0

In [3]:
cardiodf = df[["age", "gender", "height", "weight", "ap_hi", "ap_lo",
              "cholesterol", "gluc", "smoke", "alco", "active", "cardio"]]
cardiodf.head(20)

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,47,1,156,56.0,100,60,1,1,0,0,0,0
5,60,1,151,67.0,120,80,2,2,0,0,0,0
6,60,1,157,93.0,130,80,3,1,0,0,1,0
7,61,2,178,95.0,130,90,3,3,0,0,1,1
8,48,1,158,71.0,110,70,1,1,0,0,1,0
9,54,1,164,68.0,110,60,1,1,0,0,0,0
10,61,1,169,80.0,120,80,1,1,0,0,1,0
11,51,2,173,60.0,120,80,1,1,0,0,1,0
12,40,2,165,60.0,120,80,1,1,0,0,0,0
13,54,1,158,78.0,110,70,1,1,0,0,1,0
14,39,2,181,95.0,130,90,1,1,1,1,1,0
15,45,2,172,112.0,120,80,1,1,0,0,0,1
16,58,1,170,75.0,130,70,1,1,0,0,0,0
17,45,1,158,52.0,110,70,1,3,0,0,1,0
18,47,1,154,68.0,100,70,1,1,0,0,0,0
19,59,2,162,56.0,120,70,1,1,1,0,1,0

In [4]:
X = cardiodf.drop("cardio", axis=1)
y = cardiodf["cardio"]
feature_names = X.columns
print(X.shape, y.shape)

(70000, 11) (70000,)

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [6]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [7]:
from keras.utils import to_categorical

# one-hot encoding y feature
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

# one-hot encoding X features
X_train_categorical = to_categorical(X_train[["gluc", "smoke", "alco", "active", "cholesterol", "gender"]])
X_test_categorical = to_categorical(X_test[["gluc", "smoke", "alco", "active", "cholesterol", "gender"]])

Using TensorFlow backend.

In [8]:
from keras.models import Sequential
from keras.layers import Dense

deep_model = Sequential()
deep_model.add(Dense(units=6, activation='relu', input_dim=11))
deep_model.add(Dense(units=6, activation='relu'))
deep_model.add(Dense(units=2, activation='softmax'))

In [9]:
deep_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [10]:
deep_model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 2s - loss: 0.6473 - accuracy: 0.6220
Epoch 2/100
 - 2s - loss: 0.5987 - accuracy: 0.6868
Epoch 3/100
 - 2s - loss: 0.5675 - accuracy: 0.7220
Epoch 4/100
 - 1s - loss: 0.5597 - accuracy: 0.7284
Epoch 5/100
 - 1s - loss: 0.5563 - accuracy: 0.7302
Epoch 6/100
 - 1s - loss: 0.5541 - accuracy: 0.7297
Epoch 7/100
 - 1s - loss: 0.5521 - accuracy: 0.7303
Epoch 8/100
 - 1s - loss: 0.5499 - accuracy: 0.7318
Epoch 9/100
 - 1s - loss: 0.5484 - accuracy: 0.7321
Epoch 10/100
 - 2s - loss: 0.5471 - accuracy: 0.7315
Epoch 11/100
 - 2s - loss: 0.5464 - accuracy: 0.7322
Epoch 12/100
 - 2s - loss: 0.5457 - accuracy: 0.7329
Epoch 13/100
 - 2s - loss: 0.5449 - accuracy: 0.7327
Epoch 14/100
 - 2s - loss: 0.5444 - accuracy: 0.7348
Epoch 15/100
 - 2s - loss: 0.5442 - accuracy: 0.7342
Epoch 16/100
 - 1s - loss: 0.5439 - accuracy: 0.7348
Epoch 17/100
 - 1s - loss: 0.5438 - accuracy: 0.7333
Epoch 18/100
 - 2s - loss: 0.5436 - accuracy: 0.7345
Epoch 19/100
 - 1s - loss: 0.5433 - accuracy: 0.7351
Epoch 20/100
 - 1s - loss: 0.5434 - accuracy: 0.7346
Epoch 21/100
 - 1s - loss: 0.5432 - accuracy: 0.7345
Epoch 22/100
 - 1s - loss: 0.5433 - accuracy: 0.7335
Epoch 23/100
 - 2s - loss: 0.5433 - accuracy: 0.7348
Epoch 24/100
 - 1s - loss: 0.5431 - accuracy: 0.7352
Epoch 25/100
 - 1s - loss: 0.5430 - accuracy: 0.7342
Epoch 26/100
 - 1s - loss: 0.5430 - accuracy: 0.7340
Epoch 27/100
 - 1s - loss: 0.5428 - accuracy: 0.7343
Epoch 28/100
 - 1s - loss: 0.5424 - accuracy: 0.7342
Epoch 29/100
 - 1s - loss: 0.5427 - accuracy: 0.7345
Epoch 30/100
 - 1s - loss: 0.5426 - accuracy: 0.7353
Epoch 31/100
 - 2s - loss: 0.5427 - accuracy: 0.7347
Epoch 32/100
 - 1s - loss: 0.5427 - accuracy: 0.7345
Epoch 33/100
 - 1s - loss: 0.5426 - accuracy: 0.7335
Epoch 34/100
 - 1s - loss: 0.5425 - accuracy: 0.7359
Epoch 35/100
 - 1s - loss: 0.5421 - accuracy: 0.7352
Epoch 36/100
 - 1s - loss: 0.5424 - accuracy: 0.7347
Epoch 37/100
 - 1s - loss: 0.5423 - accuracy: 0.7350
Epoch 38/100
 - 2s - loss: 0.5422 - accuracy: 0.7357
Epoch 39/100
 - 1s - loss: 0.5422 - accuracy: 0.7352
Epoch 40/100
 - 1s - loss: 0.5420 - accuracy: 0.7351
Epoch 41/100
 - 1s - loss: 0.5423 - accuracy: 0.7353
Epoch 42/100
 - 2s - loss: 0.5421 - accuracy: 0.7354
Epoch 43/100
 - 2s - loss: 0.5422 - accuracy: 0.7352
Epoch 44/100
 - 1s - loss: 0.5422 - accuracy: 0.7352
Epoch 45/100
 - 1s - loss: 0.5423 - accuracy: 0.7358
Epoch 46/100
 - 2s - loss: 0.5421 - accuracy: 0.7347
Epoch 47/100
 - 1s - loss: 0.5420 - accuracy: 0.7358
Epoch 48/100
 - 1s - loss: 0.5421 - accuracy: 0.7356
Epoch 49/100
 - 1s - loss: 0.5420 - accuracy: 0.7356
Epoch 50/100
 - 1s - loss: 0.5421 - accuracy: 0.7355
Epoch 51/100
 - 1s - loss: 0.5421 - accuracy: 0.7353
Epoch 52/100
 - 1s - loss: 0.5422 - accuracy: 0.7358
Epoch 53/100
 - 1s - loss: 0.5423 - accuracy: 0.7351
Epoch 54/100
 - 2s - loss: 0.5423 - accuracy: 0.7346
Epoch 55/100
 - 2s - loss: 0.5420 - accuracy: 0.7341
Epoch 56/100
 - 2s - loss: 0.5421 - accuracy: 0.7351
Epoch 57/100
 - 2s - loss: 0.5419 - accuracy: 0.7364
Epoch 58/100
 - 1s - loss: 0.5421 - accuracy: 0.7348
Epoch 59/100
 - 1s - loss: 0.5419 - accuracy: 0.7355
Epoch 60/100
 - 1s - loss: 0.5422 - accuracy: 0.7352
Epoch 61/100
 - 1s - loss: 0.5419 - accuracy: 0.7351
Epoch 62/100
 - 1s - loss: 0.5420 - accuracy: 0.7342
Epoch 63/100
 - 1s - loss: 0.5419 - accuracy: 0.7355
Epoch 64/100
 - 2s - loss: 0.5420 - accuracy: 0.7352
Epoch 65/100
 - 1s - loss: 0.5420 - accuracy: 0.7355
Epoch 66/100
 - 1s - loss: 0.5419 - accuracy: 0.7357
Epoch 67/100
 - 1s - loss: 0.5418 - accuracy: 0.7354
Epoch 68/100
 - 1s - loss: 0.5422 - accuracy: 0.7350
Epoch 69/100
 - 1s - loss: 0.5420 - accuracy: 0.7357
Epoch 70/100
 - 1s - loss: 0.5419 - accuracy: 0.7357
Epoch 71/100
 - 2s - loss: 0.5419 - accuracy: 0.7363
Epoch 72/100
 - 1s - loss: 0.5419 - accuracy: 0.7353
Epoch 73/100
 - 1s - loss: 0.5419 - accuracy: 0.7353
Epoch 74/100
 - 1s - loss: 0.5418 - accuracy: 0.7347
Epoch 75/100
 - 2s - loss: 0.5418 - accuracy: 0.7361
Epoch 76/100
 - 1s - loss: 0.5417 - accuracy: 0.7360
Epoch 77/100
 - 2s - loss: 0.5420 - accuracy: 0.7358
Epoch 78/100
 - 1s - loss: 0.5419 - accuracy: 0.7353
Epoch 79/100
 - 1s - loss: 0.5419 - accuracy: 0.7346
Epoch 80/100
 - 1s - loss: 0.5417 - accuracy: 0.7354
Epoch 81/100
 - 1s - loss: 0.5418 - accuracy: 0.7357
Epoch 82/100
 - 1s - loss: 0.5418 - accuracy: 0.7353
Epoch 83/100
 - 2s - loss: 0.5416 - accuracy: 0.7361
Epoch 84/100
 - 2s - loss: 0.5418 - accuracy: 0.7347
Epoch 85/100
 - 2s - loss: 0.5419 - accuracy: 0.7355
Epoch 86/100
 - 1s - loss: 0.5417 - accuracy: 0.7358
Epoch 87/100
 - 1s - loss: 0.5417 - accuracy: 0.7362
Epoch 88/100
 - 1s - loss: 0.5418 - accuracy: 0.7355
Epoch 89/100
 - 2s - loss: 0.5419 - accuracy: 0.7350
Epoch 90/100
 - 2s - loss: 0.5417 - accuracy: 0.7350
Epoch 91/100
 - 2s - loss: 0.5418 - accuracy: 0.7351
Epoch 92/100
 - 2s - loss: 0.5418 - accuracy: 0.7345
Epoch 93/100
 - 2s - loss: 0.5418 - accuracy: 0.7353
Epoch 94/100
 - 2s - loss: 0.5417 - accuracy: 0.7356
Epoch 95/100
 - 1s - loss: 0.5418 - accuracy: 0.7349
Epoch 96/100
 - 1s - loss: 0.5416 - accuracy: 0.7358
Epoch 97/100
 - 1s - loss: 0.5417 - accuracy: 0.7354
Epoch 98/100
 - 1s - loss: 0.5416 - accuracy: 0.7345
Epoch 99/100
 - 1s - loss: 0.5416 - accuracy: 0.7358
Epoch 100/100
 - 2s - loss: 0.5418 - accuracy: 0.7359

In [11]:
# DEEP LEARNING MODEL
model_loss, model_accuracy = deep_model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(f"Deep Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Deep Neural Network - Loss: 0.5422107822690692, Accuracy: 0.7333142757415771

In [13]:
deep_model.save("neural_network2.h5")

In [15]:
from keras.models import load_model
neural_network2 = load_model("neural_network2.h5")

In [16]:
model_loss, model_accuracy = neural_network2.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Deep Learning Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Deep Learning Neural Network - Loss: 0.5422107822690692, Accuracy: 0.7333142757415771