In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import sklearn.datasets
import pandas as pd

# Import Data

In [2]:
df = pd.read_csv("../Resources/heart.csv", sep=";")
df["age"] = (df["age"]/365).apply(np.floor).astype(int)
df.head(20)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0
5,8,60,1,151,67.0,120,80,2,2,0,0,0,0
6,9,60,1,157,93.0,130,80,3,1,0,0,1,0
7,12,61,2,178,95.0,130,90,3,3,0,0,1,1
8,13,48,1,158,71.0,110,70,1,1,0,0,1,0
9,14,54,1,164,68.0,110,60,1,1,0,0,0,0
10,15,61,1,169,80.0,120,80,1,1,0,0,1,0
11,16,51,2,173,60.0,120,80,1,1,0,0,1,0
12,18,40,2,165,60.0,120,80,1,1,0,0,0,0
13,21,54,1,158,78.0,110,70,1,1,0,0,1,0
14,23,39,2,181,95.0,130,90,1,1,1,1,1,0
15,24,45,2,172,112.0,120,80,1,1,0,0,0,1
16,25,58,1,170,75.0,130,70,1,1,0,0,0,0
17,27,45,1,158,52.0,110,70,1,3,0,0,1,0
18,28,47,1,154,68.0,100,70,1,1,0,0,0,0
19,29,59,2,162,56.0,120,70,1,1,1,0,1,0

# Data Preprocessing

In [3]:
cardiodf = df[["age", "gender", "height", "weight", "ap_hi", "ap_lo",
              "cholesterol", "gluc", "smoke", "alco", "active", "cardio"]]
cardiodf.head(20)

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,47,1,156,56.0,100,60,1,1,0,0,0,0
5,60,1,151,67.0,120,80,2,2,0,0,0,0
6,60,1,157,93.0,130,80,3,1,0,0,1,0
7,61,2,178,95.0,130,90,3,3,0,0,1,1
8,48,1,158,71.0,110,70,1,1,0,0,1,0
9,54,1,164,68.0,110,60,1,1,0,0,0,0
10,61,1,169,80.0,120,80,1,1,0,0,1,0
11,51,2,173,60.0,120,80,1,1,0,0,1,0
12,40,2,165,60.0,120,80,1,1,0,0,0,0
13,54,1,158,78.0,110,70,1,1,0,0,1,0
14,39,2,181,95.0,130,90,1,1,1,1,1,0
15,45,2,172,112.0,120,80,1,1,0,0,0,1
16,58,1,170,75.0,130,70,1,1,0,0,0,0
17,45,1,158,52.0,110,70,1,3,0,0,1,0
18,47,1,154,68.0,100,70,1,1,0,0,0,0
19,59,2,162,56.0,120,70,1,1,1,0,1,0

In [4]:
X = cardiodf.drop("cardio", axis=1)
y = cardiodf["cardio"]
feature_names = X.columns
print(X.shape, y.shape)

(70000, 11) (70000,)

# Train_test_split

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# StandardScaler

In [6]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [7]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# One-Hot Encoding

In [8]:
from keras.utils import to_categorical

# one-hot encoding y feature
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

Using TensorFlow backend.

# Create the Neural Network

In [9]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

model.add(Dense(units=6, activation='relu', input_dim=11))
model.add(Dense(units=2, activation='softmax'))

In [10]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 2s - loss: 0.6306 - accuracy: 0.6477
Epoch 2/100
 - 1s - loss: 0.5904 - accuracy: 0.6985
Epoch 3/100
 - 1s - loss: 0.5704 - accuracy: 0.7253
Epoch 4/100
 - 1s - loss: 0.5658 - accuracy: 0.7292
Epoch 5/100
 - 1s - loss: 0.5645 - accuracy: 0.7293
Epoch 6/100
 - 1s - loss: 0.5640 - accuracy: 0.7286
Epoch 7/100
 - 1s - loss: 0.5632 - accuracy: 0.7292
Epoch 8/100
 - 1s - loss: 0.5630 - accuracy: 0.7286
Epoch 9/100
 - 1s - loss: 0.5625 - accuracy: 0.7294
Epoch 10/100
 - 1s - loss: 0.5623 - accuracy: 0.7293
Epoch 11/100
 - 1s - loss: 0.5621 - accuracy: 0.7300
Epoch 12/100
 - 2s - loss: 0.5620 - accuracy: 0.7289
Epoch 13/100
 - 2s - loss: 0.5616 - accuracy: 0.7294
Epoch 14/100
 - 2s - loss: 0.5614 - accuracy: 0.7300
Epoch 15/100
 - 2s - loss: 0.5612 - accuracy: 0.7297
Epoch 16/100
 - 1s - loss: 0.5611 - accuracy: 0.7293
Epoch 17/100
 - 1s - loss: 0.5609 - accuracy: 0.7297
Epoch 18/100
 - 1s - loss: 0.5609 - accuracy: 0.7297
Epoch 19/100
 - 1s - loss: 0.5608 - accuracy: 0.7296
Epoch 20/100
 - 1s - loss: 0.5606 - accuracy: 0.7292
Epoch 21/100
 - 1s - loss: 0.5605 - accuracy: 0.7297
Epoch 22/100
 - 1s - loss: 0.5603 - accuracy: 0.7299
Epoch 23/100
 - 1s - loss: 0.5601 - accuracy: 0.7298
Epoch 24/100
 - 1s - loss: 0.5601 - accuracy: 0.7288
Epoch 25/100
 - 1s - loss: 0.5599 - accuracy: 0.7295
Epoch 26/100
 - 2s - loss: 0.5597 - accuracy: 0.7293
Epoch 27/100
 - 1s - loss: 0.5593 - accuracy: 0.7300
Epoch 28/100
 - 2s - loss: 0.5588 - accuracy: 0.7292
Epoch 29/100
 - 2s - loss: 0.5581 - accuracy: 0.7300
Epoch 30/100
 - 2s - loss: 0.5572 - accuracy: 0.7306
Epoch 31/100
 - 2s - loss: 0.5558 - accuracy: 0.7302
Epoch 32/100
 - 2s - loss: 0.5537 - accuracy: 0.7320
Epoch 33/100
 - 2s - loss: 0.5510 - accuracy: 0.7317
Epoch 34/100
 - 1s - loss: 0.5490 - accuracy: 0.7316
Epoch 35/100
 - 2s - loss: 0.5476 - accuracy: 0.7314
Epoch 36/100
 - 2s - loss: 0.5467 - accuracy: 0.7322
Epoch 37/100
 - 2s - loss: 0.5462 - accuracy: 0.7326
Epoch 38/100
 - 2s - loss: 0.5459 - accuracy: 0.7326
Epoch 39/100
 - 2s - loss: 0.5457 - accuracy: 0.7339
Epoch 40/100
 - 2s - loss: 0.5455 - accuracy: 0.7327
Epoch 41/100
 - 2s - loss: 0.5451 - accuracy: 0.7339
Epoch 42/100
 - 2s - loss: 0.5450 - accuracy: 0.7328
Epoch 43/100
 - 2s - loss: 0.5450 - accuracy: 0.7331
Epoch 44/100
 - 2s - loss: 0.5446 - accuracy: 0.7340
Epoch 45/100
 - 2s - loss: 0.5446 - accuracy: 0.7339
Epoch 46/100
 - 2s - loss: 0.5445 - accuracy: 0.7343
Epoch 47/100
 - 2s - loss: 0.5445 - accuracy: 0.7325
Epoch 48/100
 - 2s - loss: 0.5443 - accuracy: 0.7343
Epoch 49/100
 - 2s - loss: 0.5443 - accuracy: 0.7335
Epoch 50/100
 - 2s - loss: 0.5443 - accuracy: 0.7338
Epoch 51/100
 - 2s - loss: 0.5442 - accuracy: 0.7333
Epoch 52/100
 - 2s - loss: 0.5441 - accuracy: 0.7343
Epoch 53/100
 - 1s - loss: 0.5442 - accuracy: 0.7338
Epoch 54/100
 - 2s - loss: 0.5440 - accuracy: 0.7343
Epoch 55/100
 - 1s - loss: 0.5439 - accuracy: 0.7346
Epoch 56/100
 - 1s - loss: 0.5439 - accuracy: 0.7333
Epoch 57/100
 - 1s - loss: 0.5438 - accuracy: 0.7348
Epoch 58/100
 - 1s - loss: 0.5437 - accuracy: 0.7343
Epoch 59/100
 - 2s - loss: 0.5437 - accuracy: 0.7353
Epoch 60/100
 - 1s - loss: 0.5436 - accuracy: 0.7341
Epoch 61/100
 - 1s - loss: 0.5437 - accuracy: 0.7346
Epoch 62/100
 - 1s - loss: 0.5435 - accuracy: 0.7356
Epoch 63/100
 - 1s - loss: 0.5436 - accuracy: 0.7351
Epoch 64/100
 - 1s - loss: 0.5435 - accuracy: 0.7352
Epoch 65/100
 - 1s - loss: 0.5434 - accuracy: 0.7339
Epoch 66/100
 - 1s - loss: 0.5434 - accuracy: 0.7348
Epoch 67/100
 - 1s - loss: 0.5433 - accuracy: 0.7354
Epoch 68/100
 - 1s - loss: 0.5432 - accuracy: 0.7345
Epoch 69/100
 - 1s - loss: 0.5432 - accuracy: 0.7347
Epoch 70/100
 - 1s - loss: 0.5432 - accuracy: 0.7352
Epoch 71/100
 - 1s - loss: 0.5431 - accuracy: 0.7347
Epoch 72/100
 - 1s - loss: 0.5431 - accuracy: 0.7342
Epoch 73/100
 - 1s - loss: 0.5432 - accuracy: 0.7345
Epoch 74/100
 - 1s - loss: 0.5431 - accuracy: 0.7338
Epoch 75/100
 - 1s - loss: 0.5432 - accuracy: 0.7352
Epoch 76/100
 - 2s - loss: 0.5430 - accuracy: 0.7349
Epoch 77/100
 - 2s - loss: 0.5431 - accuracy: 0.7342
Epoch 78/100
 - 2s - loss: 0.5431 - accuracy: 0.7353
Epoch 79/100
 - 2s - loss: 0.5431 - accuracy: 0.7344
Epoch 80/100
 - 2s - loss: 0.5430 - accuracy: 0.7340
Epoch 81/100
 - 2s - loss: 0.5430 - accuracy: 0.7344
Epoch 82/100
 - 2s - loss: 0.5434 - accuracy: 0.7343
Epoch 83/100
 - 2s - loss: 0.5429 - accuracy: 0.7348
Epoch 84/100
 - 2s - loss: 0.5428 - accuracy: 0.7344
Epoch 85/100
 - 2s - loss: 0.5432 - accuracy: 0.7346
Epoch 86/100
 - 1s - loss: 0.5432 - accuracy: 0.7347
Epoch 87/100
 - 1s - loss: 0.5433 - accuracy: 0.7348
Epoch 88/100
 - 1s - loss: 0.5431 - accuracy: 0.7342
Epoch 89/100
 - 2s - loss: 0.5431 - accuracy: 0.7353
Epoch 90/100
 - 2s - loss: 0.5432 - accuracy: 0.7351
Epoch 91/100
 - 2s - loss: 0.5432 - accuracy: 0.7340
Epoch 92/100
 - 2s - loss: 0.5432 - accuracy: 0.7344
Epoch 93/100
 - 2s - loss: 0.5430 - accuracy: 0.7341
Epoch 94/100
 - 2s - loss: 0.5430 - accuracy: 0.7349
Epoch 95/100
 - 1s - loss: 0.5433 - accuracy: 0.7342
Epoch 96/100
 - 1s - loss: 0.5432 - accuracy: 0.7337
Epoch 97/100
 - 2s - loss: 0.5430 - accuracy: 0.7353
Epoch 98/100
 - 2s - loss: 0.5429 - accuracy: 0.7350
Epoch 99/100
 - 2s - loss: 0.5429 - accuracy: 0.7348
Epoch 100/100
 - 2s - loss: 0.5432 - accuracy: 0.7345

In [11]:
# STANDARD MODEL
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

print("-------------------------------------------------------------------")

Normal Neural Network - Loss: 0.5434379187038967, Accuracy: 0.7323428392410278
-------------------------------------------------------------------

In [12]:
model.save("neural_network1.h5")

In [13]:
from keras.models import load_model
neural_network1 = load_model("neural_network1.h5")

In [14]:
model_loss, model_accuracy = neural_network1.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Neural Network - Loss: 0.5434379187038967, Accuracy: 0.7323428392410278