In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import sklearn.datasets
import pandas as pd

# Import Data

In [2]:
df = pd.read_csv("../Resources/heart.csv", sep=";")
df["age"] = (df["age"]/365).apply(np.floor).astype(int)
df.head(20)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0
5,8,60,1,151,67.0,120,80,2,2,0,0,0,0
6,9,60,1,157,93.0,130,80,3,1,0,0,1,0
7,12,61,2,178,95.0,130,90,3,3,0,0,1,1
8,13,48,1,158,71.0,110,70,1,1,0,0,1,0
9,14,54,1,164,68.0,110,60,1,1,0,0,0,0
10,15,61,1,169,80.0,120,80,1,1,0,0,1,0
11,16,51,2,173,60.0,120,80,1,1,0,0,1,0
12,18,40,2,165,60.0,120,80,1,1,0,0,0,0
13,21,54,1,158,78.0,110,70,1,1,0,0,1,0
14,23,39,2,181,95.0,130,90,1,1,1,1,1,0
15,24,45,2,172,112.0,120,80,1,1,0,0,0,1
16,25,58,1,170,75.0,130,70,1,1,0,0,0,0
17,27,45,1,158,52.0,110,70,1,3,0,0,1,0
18,28,47,1,154,68.0,100,70,1,1,0,0,0,0
19,29,59,2,162,56.0,120,70,1,1,1,0,1,0

# Data Preprocessing

In [3]:
cardiodf = df[["age", "gender", "height", "weight", "ap_hi", "ap_lo",
              "cholesterol", "gluc", "smoke", "alco", "active", "cardio"]]
cardiodf.head(20)

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,47,1,156,56.0,100,60,1,1,0,0,0,0
5,60,1,151,67.0,120,80,2,2,0,0,0,0
6,60,1,157,93.0,130,80,3,1,0,0,1,0
7,61,2,178,95.0,130,90,3,3,0,0,1,1
8,48,1,158,71.0,110,70,1,1,0,0,1,0
9,54,1,164,68.0,110,60,1,1,0,0,0,0
10,61,1,169,80.0,120,80,1,1,0,0,1,0
11,51,2,173,60.0,120,80,1,1,0,0,1,0
12,40,2,165,60.0,120,80,1,1,0,0,0,0
13,54,1,158,78.0,110,70,1,1,0,0,1,0
14,39,2,181,95.0,130,90,1,1,1,1,1,0
15,45,2,172,112.0,120,80,1,1,0,0,0,1
16,58,1,170,75.0,130,70,1,1,0,0,0,0
17,45,1,158,52.0,110,70,1,3,0,0,1,0
18,47,1,154,68.0,100,70,1,1,0,0,0,0
19,59,2,162,56.0,120,70,1,1,1,0,1,0

In [4]:
X = cardiodf.drop("cardio", axis=1)
y = cardiodf["cardio"]
feature_names = X.columns
print(X.shape, y.shape)

(70000, 11) (70000,)

# Train_test_split

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# StandardScaler

In [6]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [7]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# One-Hot Encoding

In [9]:
from keras.utils import to_categorical

# one-hot encoding y feature
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

In [10]:
# one-hot encoding X features
X_train_categorical = to_categorical(X_train[["gluc", "smoke", "alco", "active", "cholesterol", "gender"]])
X_test_categorical = to_categorical(X_test[["gluc", "smoke", "alco", "active", "cholesterol", "gender"]])

# Create the Neural Network

In [11]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

model.add(Dense(units=6, activation='relu', input_dim=11))
model.add(Dense(units=2, activation='softmax'))

In [12]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 2s - loss: 0.6585 - accuracy: 0.6186
Epoch 2/100
 - 2s - loss: 0.6064 - accuracy: 0.6819
Epoch 3/100
 - 1s - loss: 0.5785 - accuracy: 0.7165
Epoch 4/100
 - 1s - loss: 0.5702 - accuracy: 0.7265
Epoch 5/100
 - 1s - loss: 0.5680 - accuracy: 0.7270
Epoch 6/100
 - 2s - loss: 0.5670 - accuracy: 0.7271
Epoch 7/100
 - 1s - loss: 0.5661 - accuracy: 0.7283
Epoch 8/100
 - 2s - loss: 0.5658 - accuracy: 0.7281
Epoch 9/100
 - 2s - loss: 0.5657 - accuracy: 0.7289
Epoch 10/100
 - 2s - loss: 0.5651 - accuracy: 0.7299
Epoch 11/100
 - 2s - loss: 0.5648 - accuracy: 0.7298
Epoch 12/100
 - 1s - loss: 0.5646 - accuracy: 0.7294
Epoch 13/100
 - 1s - loss: 0.5644 - accuracy: 0.7293
Epoch 14/100
 - 1s - loss: 0.5640 - accuracy: 0.7291
Epoch 15/100
 - 2s - loss: 0.5639 - accuracy: 0.7294
Epoch 16/100
 - 2s - loss: 0.5636 - accuracy: 0.7301
Epoch 17/100
 - 1s - loss: 0.5635 - accuracy: 0.7286
Epoch 18/100
 - 2s - loss: 0.5634 - accuracy: 0.7292
Epoch 19/100
 - 2s - loss: 0.5632 - accuracy: 0.7296
Epoch 20/100
 - 1s - loss: 0.5632 - accuracy: 0.7295
Epoch 21/100
 - 2s - loss: 0.5632 - accuracy: 0.7295
Epoch 22/100
 - 2s - loss: 0.5632 - accuracy: 0.7302
Epoch 23/100
 - 2s - loss: 0.5630 - accuracy: 0.7302
Epoch 24/100
 - 2s - loss: 0.5631 - accuracy: 0.7294
Epoch 25/100
 - 1s - loss: 0.5629 - accuracy: 0.7300
Epoch 26/100
 - 1s - loss: 0.5631 - accuracy: 0.7301
Epoch 27/100
 - 1s - loss: 0.5628 - accuracy: 0.7303
Epoch 28/100
 - 1s - loss: 0.5631 - accuracy: 0.7295
Epoch 29/100
 - 1s - loss: 0.5630 - accuracy: 0.7295
Epoch 30/100
 - 1s - loss: 0.5630 - accuracy: 0.7297
Epoch 31/100
 - 1s - loss: 0.5628 - accuracy: 0.7292
Epoch 32/100
 - 1s - loss: 0.5629 - accuracy: 0.7308
Epoch 33/100
 - 1s - loss: 0.5628 - accuracy: 0.7301
Epoch 34/100
 - 1s - loss: 0.5629 - accuracy: 0.7298
Epoch 35/100
 - 1s - loss: 0.5627 - accuracy: 0.7293
Epoch 36/100
 - 1s - loss: 0.5629 - accuracy: 0.7297
Epoch 37/100
 - 1s - loss: 0.5628 - accuracy: 0.7304
Epoch 38/100
 - 1s - loss: 0.5627 - accuracy: 0.7297
Epoch 39/100
 - 1s - loss: 0.5627 - accuracy: 0.7297
Epoch 40/100
 - 1s - loss: 0.5628 - accuracy: 0.7306
Epoch 41/100
 - 1s - loss: 0.5629 - accuracy: 0.7293
Epoch 42/100
 - 1s - loss: 0.5627 - accuracy: 0.7302
Epoch 43/100
 - 1s - loss: 0.5626 - accuracy: 0.7296
Epoch 44/100
 - 1s - loss: 0.5627 - accuracy: 0.7306
Epoch 45/100
 - 2s - loss: 0.5626 - accuracy: 0.7305
Epoch 46/100
 - 2s - loss: 0.5629 - accuracy: 0.7308
Epoch 47/100
 - 1s - loss: 0.5629 - accuracy: 0.7304
Epoch 48/100
 - 1s - loss: 0.5625 - accuracy: 0.7302
Epoch 49/100
 - 1s - loss: 0.5627 - accuracy: 0.7308
Epoch 50/100
 - 1s - loss: 0.5628 - accuracy: 0.7303
Epoch 51/100
 - 1s - loss: 0.5626 - accuracy: 0.7314
Epoch 52/100
 - 1s - loss: 0.5626 - accuracy: 0.7298
Epoch 53/100
 - 1s - loss: 0.5629 - accuracy: 0.7302
Epoch 54/100
 - 1s - loss: 0.5627 - accuracy: 0.7297
Epoch 55/100
 - 1s - loss: 0.5626 - accuracy: 0.7300
Epoch 56/100
 - 1s - loss: 0.5626 - accuracy: 0.7294
Epoch 57/100
 - 1s - loss: 0.5626 - accuracy: 0.7306
Epoch 58/100
 - 1s - loss: 0.5624 - accuracy: 0.7309
Epoch 59/100
 - 1s - loss: 0.5627 - accuracy: 0.7304
Epoch 60/100
 - 1s - loss: 0.5626 - accuracy: 0.7300
Epoch 61/100
 - 1s - loss: 0.5626 - accuracy: 0.7308
Epoch 62/100
 - 1s - loss: 0.5625 - accuracy: 0.7298
Epoch 63/100
 - 1s - loss: 0.5624 - accuracy: 0.7300
Epoch 64/100
 - 1s - loss: 0.5623 - accuracy: 0.7298
Epoch 65/100
 - 1s - loss: 0.5621 - accuracy: 0.7294
Epoch 66/100
 - 1s - loss: 0.5618 - accuracy: 0.7312
Epoch 67/100
 - 1s - loss: 0.5615 - accuracy: 0.7299
Epoch 68/100
 - 1s - loss: 0.5611 - accuracy: 0.7303
Epoch 69/100
 - 1s - loss: 0.5600 - accuracy: 0.7310
Epoch 70/100
 - 1s - loss: 0.5589 - accuracy: 0.7312
Epoch 71/100
 - 1s - loss: 0.5567 - accuracy: 0.7320
Epoch 72/100
 - 1s - loss: 0.5543 - accuracy: 0.7326
Epoch 73/100
 - 1s - loss: 0.5520 - accuracy: 0.7323
Epoch 74/100
 - 1s - loss: 0.5507 - accuracy: 0.7306
Epoch 75/100
 - 2s - loss: 0.5495 - accuracy: 0.7319
Epoch 76/100
 - 2s - loss: 0.5488 - accuracy: 0.7315
Epoch 77/100
 - 1s - loss: 0.5484 - accuracy: 0.7310
Epoch 78/100
 - 2s - loss: 0.5480 - accuracy: 0.7317
Epoch 79/100
 - 1s - loss: 0.5478 - accuracy: 0.7317
Epoch 80/100
 - 1s - loss: 0.5475 - accuracy: 0.7312
Epoch 81/100
 - 2s - loss: 0.5474 - accuracy: 0.7309
Epoch 82/100
 - 1s - loss: 0.5472 - accuracy: 0.7320
Epoch 83/100
 - 2s - loss: 0.5470 - accuracy: 0.7326
Epoch 84/100
 - 1s - loss: 0.5470 - accuracy: 0.7308
Epoch 85/100
 - 2s - loss: 0.5470 - accuracy: 0.7316
Epoch 86/100
 - 1s - loss: 0.5469 - accuracy: 0.7310
Epoch 87/100
 - 1s - loss: 0.5467 - accuracy: 0.7307
Epoch 88/100
 - 2s - loss: 0.5467 - accuracy: 0.7315
Epoch 89/100
 - 1s - loss: 0.5469 - accuracy: 0.7313
Epoch 90/100
 - 2s - loss: 0.5464 - accuracy: 0.7325
Epoch 91/100
 - 2s - loss: 0.5467 - accuracy: 0.7316
Epoch 92/100
 - 1s - loss: 0.5467 - accuracy: 0.7316
Epoch 93/100
 - 1s - loss: 0.5461 - accuracy: 0.7318
Epoch 94/100
 - 1s - loss: 0.5462 - accuracy: 0.7313
Epoch 95/100
 - 1s - loss: 0.5462 - accuracy: 0.7316
Epoch 96/100
 - 2s - loss: 0.5464 - accuracy: 0.7313
Epoch 97/100
 - 2s - loss: 0.5465 - accuracy: 0.7314
Epoch 98/100
 - 2s - loss: 0.5463 - accuracy: 0.7311
Epoch 99/100
 - 2s - loss: 0.5462 - accuracy: 0.7325
Epoch 100/100
 - 1s - loss: 0.5460 - accuracy: 0.7319

In [15]:
# STANDARD MODEL
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

print("-------------------------------------------------------------------")

Normal Neural Network - Loss: 0.5448329261507306, Accuracy: 0.7309714555740356
-------------------------------------------------------------------

In [16]:
model.save("neural_network1.h5")

In [17]:
from keras.models import load_model
neural_network1 = load_model("neural_network1.h5")

In [18]:
model_loss, model_accuracy = neural_network1.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

Neural Network - Loss: 0.5448329261507306, Accuracy: 0.7309714555740356